### ISSUE TITLE
[Bug Report] gpt.py is not working.

### ISSUE THREAD

**Issue by 95jinchul** [isaacperez/tinygpt#1] opened 2024-09-11 02:48 UTC
Hi. I am a learner for gpt and I appreciate your effort.

I want to using tinygpt but it's not working. 

first, 
In Buffer.py 
  File "/home/jovyan/tinygpt-main/src/tinygpt/buffer.py", line 696, in <listcomp>
    data = [dtype.cast(random.gauss()) for _ in range(numel)]
TypeError: Random.gauss() missing 2 required positional arguments: 'mu' and 'sigma'

There is not mu and sigma.

second,
in tokenzier.py
 File "/home/jovyan/tinygpt-main/src/tinygpt/tokenizer.py", line 80, in __init__
    self.compiled_pattern = re.compile(self.pattern, re.VERBOSE)

re.error: multiple repeat at position 203 (line 4, column 21)

There in re error. So, Could you fix it for running?

**Comment by isaacperez** [comment] 2024-09-11 11:38
Hi,

Thank you for your interest in TinyGPT!

The issue is with your Python version. I'm using Python 3.12. I made a commit to add default parameters (`mu` and `sigma`) to `random.gauss()`, so that should be resolved.

However, the regex issue is due to the lack of support for possessive quantifiers (`?+`, `++`, `*+`) in Python versions before 3.11. Unfortunately, this can't be fixed without upgrading your Python version. I’ve updated the README to reflect the minimum version requirement, so upgrading to 3.11 or higher should solve the issue.

**Closed as completed by isaacperez** 2024-09-11 11:38 UTC
